#!name=Locket Gold 🏅- NightmarketServer
#!desc=Mở khoá premium cho ứng dụng Locket Widget 
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  
#!version= 8

[General]
user-agent = Locket/1.0.0 (iPhone; iOS 26; Scale/3.00)

[Script]
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket-IPA/refs/heads/main/deleteHeader.js, timeout=120
revenuecat_fix = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket-IPA/refs/heads/main/Locket_fix.js, requires-body=true, max-size=-1, timeout=120
revenuecat_force = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket-IPA/refs/heads/main/forcegold.js, requires-body=true, max-size=-1, timeout=120

[MITM]
hostname = api.revenuecat.com, raw.githubusercontent.com
